import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {questions,topics,createSession,score,recordAnswer,blankStats,validSession} from '../dist/engine.js';
test('Every question has four distinct choices, a valid answer, source page and asset',()=>{const pages=JSON.parse(readFileSync(new URL('../dist/manual-pages.json',import.meta.url)));assert.ok(questions.length>=80);assert.equal(new Set(questions.map(q=>q.id)).size,questions.length);for(const q of questions){assert.equal(q.options.length,4,q.id);assert.equal(new Set(q.options).size,4,q.id);assert.ok(q.options[q.answer],q.id);assert.ok(q.explanation,q.id);assert.ok(pages[q.page],q.id);if(q.image)assert.ok(existsSync(new URL('../dist/'+q.image,import.meta.url)),q.image);}});
test('Quick practice and mock exams have unique questions and preserve answer mapping',()=>{for(let run=0;run<20;run++){for(const [mode,n] of [['quick',10],['exam',50]]){const s=createSession(mode);assert.equal(s.items.length,n);assert.equal(new Set(s.items.map(i=>i.id)).size,n);assert.ok(validSession(s));for(const it of s.items){assert.deepEqual([...it.order].sort(),[0,1,2,3]);it.selected=0;it.confirmed=true;}assert.equal(score(s).percent,100);}}});
test('40 out of 50 passes; 39 does not; unconfirmed choices do not count',()=>{const s=createSession('exam');s.items.forEach((it,i)=>{it.selected=0;it.confirmed=i<39});assert.equal(score(s).passed,false);s.items[39].confirmed=true;assert.equal(score(s).passed,true);assert.equal(score(s).correct,40);});
test('Wrong answers enter review once and a correct retry clears them',()=>{const stats=blankStats(),q=questions[0];recordAnswer(stats,q,1);recordAnswer(stats,q,1);assert.deepEqual(stats.missed,[q.id]);recordAnswer(stats,q,0);assert.deepEqual(stats.missed,[]);assert.equal(stats.answers,3);assert.equal(stats.correct,1);assert.deepEqual(stats.seen,[q.id]);});
test('Topic and mistake filters, invalid input and timed sessions',()=>{for(const t of topics){const s=createSession('topic',t);assert.ok(s.items.every(i=>questions.find(q=>q.id===i.id).topic===t));}assert.deepEqual(createSession('mistakes','',[questions[0].id]).items.map(i=>i.id),[questions[0].id]);assert.throws(()=>createSession('mistakes'));assert.throws(()=>createSession('topic','bad'));assert.throws(()=>createSession('bad'));const s=createSession('exam','',[],30);assert.ok(Math.abs(s.deadline-Date.now()-1800000)<1000);assert.equal(createSession('quick').deadline,null);assert.equal(validSession({...s,index:60}),false);});
