import test from 'node:test';
import assert from 'node:assert/strict';
import {questions,topics} from '../dist/questions.js';
import {kaQuestions} from '../dist/questions-ka.js';
import {translate,localizedQuestion,translations} from '../dist/i18n.js';
import {readFileSync} from 'node:fs';
test('Every English question has a complete Georgian counterpart with identical scoring metadata',()=>{assert.deepEqual(Object.keys(kaQuestions).sort(),questions.map(q=>q.id).sort());for(const q of questions){const ka=localizedQuestion(q,'ka');assert.match(ka.question,/[ა-ჰ]/,q.id);assert.match(ka.explanation,/[ა-ჰ]/,q.id);assert.equal(ka.options.length,4,q.id);assert.equal(new Set(ka.options).size,4,q.id);assert.ok(ka.options.every(s=>s.length>0),q.id);for(const key of ['id','page','answer','topic','image'])assert.equal(ka[key],q[key],q.id);assert.equal(localizedQuestion(q,'en'),q);}});
test('Topics and UI placeholders translate without missing substitutions',()=>{for(const topic of topics)assert.notEqual(translate('ka',topic),topic);for(const [key,value] of Object.entries(translations)){assert.match(value,/[ა-ჰ]/,key);const placeholders=[...key.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort();assert.deepEqual([...value.matchAll(/\{(\w+)\}/g)].map(m=>m[1]).sort(),placeholders,key);const vars=Object.fromEntries(placeholders.map(p=>[p,3]));assert.doesNotMatch(translate('ka',key,vars),/\{\w+\}/);}});
test('Literal interface keys and offline translation assets are present',()=>{const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');for(const match of app.matchAll(/\bt\('([^']+)'/g)){assert.ok(translations[match[1]],match[1]);}const sw=readFileSync(new URL('../dist/sw.js',import.meta.url),'utf8');assert.match(sw,/questions-ka\.js/);assert.match(sw,/i18n\.js/);assert.match(sw,/nj-road-ready-v10/);});
